name = "{{PROJECT_NAME}}"
main = ".open-next/worker.js"
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]
workers_dev = true

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[services]]
binding = "WORKER_SELF_REFERENCE"
service = "{{PROJECT_NAME}}"

[placement]
mode = "smart"

[[d1_databases]]
binding = "DATABASE"
database_name = "{{PROJECT_NAME}}-d1"
database_id = "{{D1_DATABASE_ID}}"
migrations_dir = "./drizzle"

[[r2_buckets]]
binding = "STORAGE"
bucket_name = "{{PROJECT_NAME}}-storage"
